#!/bin/bash
echo "Enter your age:"
read age
if [[ $age -lt 13 ]]; then
    echo "You are a child."
elif [[ $age -lt 20 ]]; then
    echo "You are a teenager."
elif [[ $age -lt 60 ]]; then
    echo "You are an adult."
else
    echo "You are a senior citizen."
fi
