#!/bin/bash
echo "Enter filename:"
read filename
if [[ -f $filename ]]; then
    echo "$filename exists. Overwrite? (y/n):"
    read answer
    if [[ $answer == "y" ]]; then
        command > $filename
    else
        echo "Exiting."
    fi
else
    command > $filename
fi
